on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Publish repository to gh-pages

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: sudo apt install build-essential dpkg-dev dh-make reprepro
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13' 

      - uses: actions/checkout@v7

      - name: Build repo
        run: ./build.sh
        env:
          KEY_PRIVKEY: ${{ secrets.KEY_PRIVKEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/repo/
